Hotfix/efisco 391
swsapien/pycfdi-transform pull request #65
Opened 2021-07-20 22:00 UTC by rbarusta

2021-07-20 22:05 UTC, Balderrama approved these changes

2021-07-20 22:07 UTC, JuanGamezSW requested changes

2021-07-20 22:07 UTC, JuanGamezSW commented on tests/Resources/pago10NonDr.xml
> +    <cfdi:Emisor Rfc="IEM110629TM5" Nombre="&quot;INGENIERIA ELECTROMECANICA DE MEXICO, SERVICIOS Y SUMINISTROS SA DE CV&quot;" RegimenFiscal="601"></cfdi:Emisor>
XML con datos reales. Considerando que es un repositorio público se sugiere cambiar Certificados, NoCertificados, RFCS, TFD, entre otros datos que pudieran ser privados.

2021-07-20 22:07 UTC, JuanGamezSW commented on tests/Resources/pago10NonDr.xml
> +            <pago10:Pago FechaPago="2021-01-13T00:00:00" FormaDePagoP="03" MonedaP="MXN" Monto="35674.83" RfcEmisorCtaOrd="BSM970519DU8" NomBancoOrdExt="SANTANDER " CtaOrdenante="0183078211" RfcEmiso
Mismo caso en el pago.

2021-07-20 22:07 UTC, JuanGamezSW commented on pycfdi_transform/sax/pagos10_handler.py
> +                        'p_dr_imp_pagado': "",
Me parece que los totales deberían ser 0.00 al ser datos que puedan causar problemas con sistemas como DB.

2021-07-21 12:47 UTC, hermesjimenez approved these changes
En la version xslt me imagino que esto no pasa ?

2021-07-21 17:14 UTC, JuanGamezSW approved these changes

2021-07-21 17:14 UTC, JuanGamezSW commented on tests/Resources/pago10NonDr.xml
> +        <tfd:TimbreFiscalDigital xmlns:tfd="http://www.sat.gob.mx/TimbreFiscalDigital" xsi:schemaLocation="http://www.sat.gob.mx/TimbreFiscalDigital http://www.sat.gob.mx/sitio_internet/cfd/TimbreFis
Yo solo mantendría la estructura de datos, por ejemplo UUID 00000000-0000-0000-0000-000000000000 y RfcProvCertif SPR190613I52, NoCertificadoSAT 30001000000400002495 por ejemplo, para que correspondan con su tipo de dato XSD.

2021-07-21 17:16 UTC, merged