Hotfix/efisco 532
swsapien/pycfdi-transform pull request #85
Opened 2021-11-05 18:44 UTC by rbarusta

2021-11-05 19:28 UTC, JuanGamezSW requested changes
Comments

2021-11-05 19:28 UTC, JuanGamezSW commented on pycfdi_transform/helpers/string_helper.py
> +        new_str = string.translate(str.maketrans('', '', '\n\t\r~'))
Yo creo que el "~" lo debería de tomar a partir de alguna configuración, porque si utilizas otro separador por ejemplo "," entonces tendrías el mismo problema.

2021-11-05 19:28 UTC, JuanGamezSW commented on tests/Resources/nomina12/nom_complete.xml
> +  <cfdi:Emisor Rfc="J&amp;O750807563" Nombre="Q" RegimenFiscal="611" />
Estos archivos no deberían de ser modificados, pues no debería cambiar el comportamiento que ya se tenía. (con la config que se comenta arriba entonces se solucionaría el problema)

2021-11-05 22:00 UTC, hermesjimenez commented
Las UT anteriores no deberían de cambiar desde mi perspectiva.

2021-11-08 18:23 UTC, JuanGamezSW approved these changes

2021-11-08 18:34 UTC, hermesjimenez approved these changes
👌

2021-11-08 18:44 UTC, merged