EFISCO-622
swsapien/pycfdi-transform pull request #98
Opened 2022-02-26 00:21 UTC by saulmtzf

- added efisco core formatters
- fixed pagos10 and efisco corp formatters
- fixed typo in nomina11 and nomina12 transformers

2022-02-26 03:34 UTC, JuanGamezSW requested changes
Falta subir la version de la libreria.

2022-02-28 17:34 UTC, Balderrama commented on pycfdi_transform/formatters/nomina12/efisco_nomina12_formatter.py
> +            cfdi_version = 'cfdi40'
yo asignaria la variable al cfdi_version para no tener doblemente quemado la string del cfdi40

2022-02-28 17:34 UTC, Balderrama commented on pycfdi_transform/formatters/nomina12/efisco_nomina12_formatter.py
>                  tdf['uuid'],
esto veo que ya estaba, pero no debería ser tfd?

2022-02-28 17:35 UTC, Balderrama approved these changes

2022-02-28 17:50 UTC, saulmtzf commented on pycfdi_transform/formatters/nomina12/efisco_nomina12_formatter.py
>                  tdf['uuid'],
fixed

2022-02-28 22:06 UTC, Koronos approved these changes

2022-03-02 16:12 UTC, merged